### ISSUE TITLE
[Bug]: Container can not restart after update to the laster version

### ISSUE THREAD

**Issue by zero178131** [advplyr/audiobookshelf#5234]
### What happened?

Container can not restart after update to the laster version

### What did you expect to happen?

reactive the container

### Steps to reproduce the issue

1. update maybe cause this issue

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs

```shell
advplyr-audiobookshelf-1
date	stream	content
2026/05/11 02:01:25	stdout	Node.js v20.20.2
2026/05/11 02:01:25	stdout	
2026/05/11 02:01:25	stdout	}
2026/05/11 02:01:25	stdout	  requireStack: []
2026/05/11 02:01:25	stdout	  code: [32m'MODULE_NOT_FOUND'[39m,
2026/05/11 02:01:25	stdout	[90m    at node:internal/main/run_main_module:28:49[39m {
2026/05/11 02:01:25	stdout	[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)[39m
2026/05/11 02:01:25	stdout	[90m    at Module._load (node:internal/modules/cjs/loader:1038:27)[39m
2026/05/11 02:01:25	stdout	[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)[39m
2026/05/11 02:01:25	stdout	Error: Cannot find module '/index.js'
2026/05/11 02:01:25	stdout	
2026/05/11 02:01:25	stdout	  ^
2026/05/11 02:01:25	stdout	  throw err;
2026/05/11 02:01:25	stdout	node:internal/modules/cjs/loader:1210
2026/05/11 02:00:34	stdout	Node.js v20.20.2
2026/05/11 02:00:34	stdout	
2026/05/11 02:00:34	stdout	}
2026/05/11 02:00:34	stdout	  requireStack: []
2026/05/11 02:00:34	stdout	  code: [32m'MODULE_NOT_FOUND'[39m,
2026/05/11 02:00:34	stdout	[90m    at node:internal/main/run_main_module:28:49[39m {
2026/05/11 02:00:34	stdout	[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)[39m
2026/05/11 02:00:34	stdout	[90m    at Module._load (node:internal/modules/cjs/loader:1038:27)[39m
2026/05/11 02:00:34	stdout	[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)[39m
2026/05/11 02:00:34	stdout	Error: Cannot find module '/index.js'
2026/05/11 02:00:34	stdout	
2026/05/11 02:00:34	stdout	  ^
2026/05/11 02:00:34	stdout	  throw err;
2026/05/11 02:00:34	stdout	node:internal/modules/cjs/loader:1210
2026/05/10 22:17:29	stdout	Node.js v20.20.2
2026/05/10 22:17:29	stdout	
2026/05/10 22:17:29	stdout	}
2026/05/10 22:17:29	stdout	  requireStack: []
2026/05/10 22:17:29	stdout	  code: [32m'MODULE_NOT_FOUND'[39m,
2026/05/10 22:17:29	stdout	[90m    at node:internal/main/run_main_module:28:49[39m {
2026/05/10 22:17:29	stdout	[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)[39m
2026/05/10 22:17:29	stdout	[90m    at Module._load (node:internal/modules/cjs/loader:1038:27)[39m
2026/05/10 22:17:29	stdout	[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)[39m
2026/05/10 22:17:29	stdout	Error: Cannot find module '/index.js'
2026/05/10 22:17:29	stdout	
2026/05/10 22:17:29	stdout	  ^
2026/05/10 22:17:29	stdout	  throw err;
2026/05/10 22:17:29	stdout	node:internal/modules/cjs/loader:1210
```

### Additional Notes

<img width="1037" height="386" alt="Image" src="https://github.com/user-attachments/assets/1d70bfa7-8414-4b84-ad4c-2f30508b2d70" />

**Comment by Vito0912** [comment]
I really hope version 2.9.0 is just written wrongly.

See https://github.com/advplyr/audiobookshelf/issues/4292#issuecomment-2887503644 how to fix it.

If you have still issues updating, you should update version for version. Not updating software for years is not a good idea. Especially if you try to upgrade at once.

**Comment by zero178131** [comment]
@Vito0912 
HI. Thank you for you quick reply.I tried edoubleoo's way. Now I can access to audioshelf.
But I be locked from use login phase. I enter my old account but system said Unauthorized.Could you gudie my how to solved this issue?

**Comment by Vito0912** [comment]
Try to load your backup for version 2.9.0 and use version ABS version 2.9.0. If you username and password works there, but not in the newest version, then you need to upgrade version for version.
So from version 2.9.0 to 2.10.0 ...

If it also does not work in 2.9.0 you likely forgot/misremember your password. For that please see https://www.audiobookshelf.org/faq/server/#how-can-i-reset-a-password as you need to manually edit the DB

**Comment by zero178131** [comment]
@Vito0912 
Thank you so much! You can close this ticket. I misremember my password.....

**Comment by Vito0912** [comment]
I am not a maintainer. You can close it at the bottom right yourself. 

Glad it worked!

<img width="368" height="55" alt="Image" src="https://github.com/user-attachments/assets/420b2446-1339-447e-b12b-71dfda3d712e" />
