### ISSUE TITLE
[Bug]: OIDC Login does not work on 2.26.0

### ISSUE THREAD

**Issue by awmath** [advplyr/audiobookshelf#4485]
### What happened?

OIDC authentikation fails on v2.26.0 but works on v2.25.1.

### What did you expect to happen?

The exact same configuration (IDP and Audiobookshelf) works on v2.25.1.

### Steps to reproduce the issue

1. Setup OIDC in IDP (Authentik in this case)
2. Setup OIDC in Audiobookshelf
3. Login to IDP with a user unknown to Audiobookshelf
4. Try to access Audiobookshelf

### Audiobookshelf version

v2.26.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
[2025-07-13 23:22:26.385] INFO: [User] openid: Auto-registering user with sub "1234567" {
  sub: '1234567',
...
}
[2025-07-13 23:22:26.387] ERROR: [OidcAuth] openid callback error: auth.generateAccessToken is not a function
TypeError: auth.generateAccessToken is not a function
    at user.createUserFromOpenIdUserInfo (/app/server/models/User.js:313:24)
    at user.findOrCreateUserFromOpenIdUserInfo (/app/server/models/User.js:293:25)
    at async OidcAuthStrategy.verifyCallback (/app/server/auth/OidcAuthStrategy.js:124:18)
[2025-07-13 23:22:26.387] ERROR: "[Auth] No data in openid callback - Unauthorized"
```

**Comment by gray-morley** [comment]
I'm seeing the same on my side when attempting to auto-register

**Comment by nwicone** [comment]
Do you know when the fix #4486 will be available ?

**Comment by nichwall** [comment]
The `:edge` docker tag is built on the latest commit to GitHub, so you can use that tag to get fixes and help test things before a full release. This tag is generally safe to use, but backups are always a good idea in case something breaks.
