### ISSUE TITLE
[Bug]: Migration issues with version 2.22 and 2.23

### ISSUE THREAD

**Issue by aznkvaj** [advplyr/audiobookshelf#4311]
### What happened?

After upgrading to 2.22 and/or 2.23 the docker no longer spin up.
The service would crash with the following error log.

### What did you expect to happen?

Expect to just start up as normal.

### Steps to reproduce the issue

1. Just changing image version to 2.22.0 or 2.23.0

### Audiobookshelf version

2.23.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
Running in production mode.
Options: CONFIG_PATH=/config, METADATA_PATH=/metadata, PORT=30067, HOST=undefined, SOURCE=docker, ROUTER_BASE_PATH=/audiobookshelf
[2025-05-19 02:50:15.146] INFO: === Starting Server ===
[2025-05-19 02:50:15.147] INFO: [Server] Init v2.23.0
[2025-05-19 02:50:15.147] INFO: [Server] Node.js Version: v20.19.2
[2025-05-19 02:50:15.147] INFO: [Server] Platform: linux
[2025-05-19 02:50:15.147] INFO: [Server] Arch: x64
[2025-05-19 02:50:15.151] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
[2025-05-19 02:50:15.180] INFO: [Database] Loading extension /usr/local/lib/nusqlite3/libnusqlite3.so
[2025-05-19 02:50:15.181] INFO: [Database] Successfully loaded extension /usr/local/lib/nusqlite3/libnusqlite3.so
[2025-05-19 02:50:15.181] INFO: [Database] Db supports unaccent and unicode foldings
[2025-05-19 02:50:15.181] INFO: [Database] Db connection was successful
[2025-05-19 02:50:15.193] ERROR: [Database] Failed to run migrations Error: Failed to copy migrations to the config directory.
    at MigrationManager.init (/app/server/managers/MigrationManager.js:54:15)
    at async Database.init (/app/server/Database.js:183:7)
    at async Server.init (/app/server/Server.js:161:5)
    at async Server.start (/app/server/Server.js:227:5) {
  [cause]: [Error: EPERM: operation not permitted, copyfile '/app/server/migrations/v2.15.1-reindex-nocase.js' -> '/config/migrations/v2.15.1-reindex-nocase.js'] {
    errno: -1,
    code: 'EPERM',
    syscall: 'copyfile',
    path: '/app/server/migrations/v2.15.1-reindex-nocase.js',
    dest: '/config/migrations/v2.15.1-reindex-nocase.js'
  }
}
[2025-05-19 02:50:15.195] FATAL: [Server] Unhandled rejection: Error: Database migration failed
    at Database.init (/app/server/Database.js:187:13)
    at async Server.init (/app/server/Server.js:161:5)
    at async Server.start (/app/server/Server.js:227:5)
promise: Promise {
  <rejected> Error: Database migration failed
      at Database.init (/app/server/Database.js:187:13)
      at async Server.init (/app/server/Server.js:161:5)
      at async Server.start (/app/server/Server.js:227:5)
}
```

**Comment by exonerationem** [comment]
After upgrading to 2.22 and/or 2.23 the docker no longer spin up.
The service would crash with the following error log.
Logs
node:internal/modules/cjs/loader:1215

  throw err;
  ^
Error: Cannot find module '/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v20.19.2

**Comment by progecon** [comment]
I am experiencing the exact same issue. Reverting the version to pre-2.22 fixes the issue

**Comment by nichwall** [comment]
@exonerationem and @progecon you are likely encountering https://github.com/advplyr/audiobookshelf/issues/4292. Please read through the discussion there to attempt to resolve.

**Comment by exonerationem** [comment]
@nichwall thanks
Under Volumes, keep only these binds:
/podcasts → host_path/Podcasts
/audiobooks → host_path/audiobooks
/config → host_path/audiobookshelf/config
/metadata → host_path/Metadata
Pull and Redeploy the new image can fix it

**Comment by mondychan** [comment]
@exonerationem can confirm, had a bind of my external folder mounted into container, which caused the issue, 
I removed the bind, redeployed, container started fine and web ui was acessible, 
after that i put the bind back in, redeployed again, and all is working fine now on 2.23, thx
